banking/urls.py
from django.urls import path
from banking import views

app_name = 'banking'

urlpatterns = [
    path('',views.index,name="index"),
    path('customers',views.customers,name="customers"),
    path('customers/search',views.customers_search,name="customers_search"),
    path('customers/transact/<int:pk>',views.transaction,name="transact"),
    path('customers/transact/<int:pk>/search',views.transact_customers_search,name="transact_customers_search"),
    path('records',views.RecordsView.as_view(),name="records"),
]

donate/urls.py
from django.urls import path
from donate import views

app_name = 'donate'

urlpatterns = [
    path('',views.index,name="index"),
    # path('paymenthandler/', views.paymenthandler, name='paymenthandler'),
]

nkbank/urls.py
from django.contrib import admin
from django.urls import path, include
from banking import views

urlpatterns = [
    path('',include('banking.urls')),
    path('admin/', admin.site.urls),
    path('donate/',include('donate.urls')),
]

banking/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class UserExtension(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #Additional Fields
    current_balance = models.IntegerField(default=0)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

class Transactions(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='withdraw_transactions')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='income_transactions')
    amount = models.IntegerField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.amount)

donate/models.py
from django.db import models

# Create your models here.
from django.db.models.fields import CharField
from django.utils.translation import gettext_lazy as _
from donate.constants import PaymentStatus

banking/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.http import HttpResponse
from banking import models
from django.views.generic import ListView
from django.contrib import messages

# Create your views here.

def index(request):
    return render(request,'banking/index.html',{})

def customers(request):
    customers_list = models.User.objects.all()
    customers_extended = models.UserExtension.objects.all()
    return render(request,'banking/customers.html',{'customers':customers_extended,})

def customers_search(request):
    query = request.GET.get('query')
    customers_extended_list = models.UserExtension.objects.filter(user__first_name__contains=query)
    customers_extended_list2 = models.UserExtension.objects.filter(user__last_name__contains=query)
    customers_extended_list = customers_extended_list.union(customers_extended_list2)
    return render(request,'banking/customers.html',{'customers':customers_extended_list,})


def transaction(request,pk):
    if request.method == "POST":
        customers = models.UserExtension.objects.all()
        to_customer = models.User.objects.get(pk=pk)
        to_customer_extended = models.UserExtension.objects.get(user=to_customer)  
        amount = request.POST.get('amount')
        from_id = request.POST.get('from_id')
        from_customer = models.User.objects.get(pk=from_id)
        from_customer_extended = models.UserExtension.objects.get(user=from_customer)
        amount = int(amount)
        from_customer_extended.current_balance -= amount
        to_customer_extended.current_balance += amount
        from_customer_extended.save()
        to_customer_extended.save()
        transact = models.Transactions()
        transact.from_user = from_customer
        transact.to_user = to_customer
        transact.amount = amount
        transact.save()
        messages.info(request, 'Transaction was successful!')
        return redirect('banking:customers')
        
    else:  
        customers = models.UserExtension.objects.all()
        from_customer = models.User.objects.get(pk=pk)
        from_customer_extended = models.UserExtension.objects.get(user=from_customer)  

        # Allow MAX AMOUNT ONLY
        return render(request,'banking/transaction.html',{'customers':customers,'id_from':pk,'from_customer':from_customer_extended,})

def transact_customers_search(request, pk):
    query = request.GET.get('query')
    customers_extended_list = models.UserExtension.objects.filter(user__first_name__contains=query)
    customers_extended_list2 = models.UserExtension.objects.filter(user__last_name__contains=query)
    customers_extended_list = customers_extended_list.union(customers_extended_list2)
    from_customer = models.User.objects.get(pk=pk)
    from_customer_extended = models.UserExtension.objects.get(user=from_customer)  
    return render(request,'banking/transaction.html',{'customers':customers_extended_list,'id_from':pk,'from_customer':from_customer_extended,})

class RecordsView(ListView):
    model = models.Transactions
    template_name = 'banking/records.html'
    context_object_name = 'records'

    ordering = ['-timestamp']

donate/views.py
from django.shortcuts import render
import razorpay
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseBadRequest
 
 
# authorize razorpay client with API Keys.
razorpay_client = razorpay.Client(
    auth=(settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET))
 
 
def index(request):
    context = {}
    return render(request, 'banking/donate.html', context=context)

templates/banking/customers.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>NK Bank - Transactions Made Easy</title>

  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'banking/assets/img/nklogo1.jpg' %}" rel="icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.9.0/font/bootstrap-icons.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">


  <!-- Vendor CSS Files -->
  <link href="{% static 'banking/assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'banking/assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'banking/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'banking/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'banking/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'banking/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'banking/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'banking/assets/css/style.css' %}" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center ">
    <div class="container d-flex justify-content-between align-items-center">

      <div class="logo">
        <h1 class="text-light"><a href="{% url 'banking:index' %}"><span>NK Bank</span></a></h1>
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="{% url 'banking:index' %}">Home</a></li>
          <li><a href="{% url 'donate:index' %}">Donate</a></li>
          <li><a class="active " href="{% url 'banking:customers' %}">Customers</a></li>
          <li><a href="{% url 'banking:records' %}">Records</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <main id="main">

    <!-- ======= Customers Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Our Customers</h2>

          <ol>
            <li><a href="{% url 'banking:index' %}">Home</a></li>
            <li>Customers</li>
          </ol>
        </div>

      </div>
    </section><!-- End Header Section -->

    {% if messages %}
    <ul class="messages"><br>
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <strong>Success!</strong> {{ message }}
        </div>
        {% endfor %}
    </ul>
    {% endif %}
    <!-- ======= Customers Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-8 entries">
            {% if customers %}
            {% for customer in customers %}
              {% if customer.user.is_staff %}

              {% else %}        
            <article class="entry">

              <h2 class="entry-title">
                <a href="blog-single.html">{{customer.user.first_name}} {{customer.user.last_name}}</a>
              </h2>

              <div class="entry-meta" style="zoom:1.4;-ms-zoom: 1.4;                      
              -webkit-zoom: 1.4;
              -moz-transform:  scale(1.4,1.4);
              -moz-transform-origin: left center;"
              >           <!-- Zoom for mozilla also-->
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-single.html">{{customer.user.email}}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">{{customer.user.date_joined}}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-currency-rupee"></i> <a href="blog-single.html">{{customer.current_balance}}</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <div style="text-align:left"><img src="{% static 'banking/assets/img/nklogo1.jpg' %}" width="45" heigh="45" style="float:left"></div>
                <div class="read-more">
                  <a href="{% url 'banking:transact' customer.user.id %}">Transact</a>
                </div>
              </div>

            </article>
            {% endif %}
            {% endfor %}
            {% else %}
              No Customers found! Search again!
            {% endif %}

          </div><!-- End customers list -->

          <div class="col-lg-4">

            <div class="sidebar">

              <h3 class="sidebar-title">Search</h3>
              <div class="sidebar-item search-form">
                <form action="{% url 'banking:customers_search' %}" method="GET">
                  <input type="text" name="query" id="query">
                  <button type="submit"><i class="bi bi-search"></i></button>
                </form>
              </div><!-- End sidebar search formn-->



            </div><!-- End sidebar -->

          </div><!-- End Customers sidebar -->

        </div>

      </div>
    </section><!-- End Customers Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">


    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'banking:index' %}">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'donate:index' %}">Donate</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'banking:customers' %}">Customers</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'banking:records' %}">Records</a></li>
            </ul>
          </div>


          <div class="col-lg-4 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              IIT Kharagpur <br>
              Kharagpur, WB 721302<br>
              West Bengal <br><br>
              <strong>Phone:</strong> +91 85150 88390<br>
              <strong>Email:</strong> nkbank@gmail.com<br>
            </p>

          </div>

          <div class="col-lg-4 col-md-6 footer-info">
            <h3>About NK Bank</h3>
            <p>NK Bank provides premium banking and transaction services both electronic and manual.
              Highest rate of interest and fastest transaction is provided to our customers.
            </p>
            <div class="social-links mt-3">
              <a href="https://github.com/NabhyaKhoria" class="twitter" target="_blank"><i class="bx bxl-github"></i></a>
              <a href="https://www.facebook.com/nkhoria/" class="facebook" target="_blank"><i class="bx bxl-facebook"></i></a>
              <a href="https://www.instagram.com/nabhya_khoria/" class="instagram"><i class="bx bxl-instagram" target="_blank"></i></a>
              <a href="https://www.linkedin.com/in/nabhya-khoria-30a601218/" class="linkedin"><i class="bx bxl-linkedin" target="_blank"></i></a>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>NK Bank</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        Designed by <a href="https://www.linkedin.com/in/nabhya-khoria-30a601218/" target="_blank">Nabhya Khoria</a>
      </div>
    </div>
  </footer>
  <!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'banking/assets/vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'banking/assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'banking/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'banking/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'banking/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'banking/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'banking/assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'banking/assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'banking/assets/js/main.js' %}"></script>

</body>

</html>

templates/banking/transaction.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>NK Bank - Transactions Made Easy</title>

  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'banking/assets/img/nklogo1.jpg' %}" rel="icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.9.0/font/bootstrap-icons.min.css">


  <!-- Vendor CSS Files -->
  <link href="{% static 'banking/assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'banking/assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'banking/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'banking/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'banking/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'banking/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'banking/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'banking/assets/css/style.css' %}" rel="stylesheet">

<style>
  .transact_btn {
    display: inline-block;
    background: #68A4C4;
    color: #fff;
    padding: 6px 20px;
    transition: 0.3s;
    font-size: 14px;
    border:none;
  }
</style>
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center ">
    <div class="container d-flex justify-content-between align-items-center">

      <div class="logo">
        <h1 class="text-light"><a href="{% url 'banking:index' %}"><span>NK Bank</span></a></h1>
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="{% url 'banking:index' %}">Home</a></li>
          <li><a href="{% url 'donate:index' %}">Donate</a></li>
          <li><a class="active " href="{% url 'banking:customers' %}">Customers</a></li>
          <li><a href="{% url 'banking:records' %}">Records</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <main id="main">

    <!-- ======= Customers Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Transact</h2>

          <ol>
            <!-- <li><a href="index.html">Home</a></li>
            <li>Customers</li> -->
                <li><Strong>Hey {{from_customer}}</Strong></li>
        </ol>
        </div>

      </div>
    </section><!-- End Customers Section -->

    <!-- ======= Customers Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-8 entries">
            {% if customers %}
            {% for customer in customers %}
              {% if customer.user.id == id_from %}
            
              {% else %}        

            <article class="entry">

              <!-- <div class="entry-img">
                <img src="{% static 'banking/assets/img/blog/blog-1.jpg' %}" alt="" class="img-fluid">
              </div> -->

              <h2 class="entry-title">
                <a href="">{{customer.user.first_name}} {{customer.user.last_name}}</a>
              </h2>

              <div class="entry-meta" style="zoom:1.4;-ms-zoom: 1.4;                      
              -webkit-zoom: 1.4;
              -moz-transform:  scale(1.4,1.4);
              -moz-transform-origin: left center;"
              >           <!-- Zoom for mozilla also-->
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="">{{customer.user.email}}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href=""><time datetime="2020-01-01">{{customer.user.date_joined}}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-currency-rupee"></i> <a href="">{{customer.current_balance}}</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <div style="text-align:left"><img src="{% static 'banking/assets/img/nklogo1.jpg' %}" width="45" heigh="45" style="float:left"></div>

                <div class="read-more">
                    <form action="{% url 'banking:transact' customer.user.pk %}" method="POST" id="transact_form">
                        {% csrf_token %}
                        <i class="bi bi-currency-rupee"></i><input type="number" name="amount" id="amount" placeholder="Amount" max="{{from_customer.current_balance}}" min="1" style="width:100px">
                        <input type="hidden" name="from_id" id="from_id" value="{{id_from}}">
                        <input class="transact_btn" type="submit" value="Transact">
                        <!-- <a class="transact_btn" onclick="transact()">Transact</a> -->
                </form>
                </div>
              </div>

            </article>
            {% endif %}
            {% endfor %}
            {% else %}
            No Customers found! Search again!
          {% endif %}
  
          </div><!-- End customer entries list -->

          <div class="col-lg-4">

            <div class="sidebar">

              <h3 class="sidebar-title">Search</h3>
              <div class="sidebar-item search-form">
                <form action="{% url 'banking:transact_customers_search' id_from %}" method="GET">
                  <input type="text" name="query" id="query">
                  <button type="submit"><i class="bi bi-search"></i></button>
                </form>
              </div><!-- End sidebar search formn-->



            </div><!-- End sidebar -->


          </div><!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->
    <script>
      function transact() {
          document.getElementById("transact_form").submit();
      }
  </script>

<!-- ======= Footer ======= -->
<footer id="footer" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">


  <div class="footer-top">
    <div class="container">
      <div class="row">

        <div class="col-lg-4 col-md-6 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'banking:index' %}">Home</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'donate:index' %}">Donate</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'banking:customers' %}">Customers</a></li>
            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'banking:records' %}">Records</a></li>
          </ul>
        </div>


        <div class="col-lg-4 col-md-6 footer-contact">
          <h4>Contact Us</h4>
          <p>
            IIT Kharagpur <br>
            Kharagpur, WB 721302<br>
            West Bengal <br><br>
            <strong>Phone:</strong> +91 85150 88390<br>
            <strong>Email:</strong> nkbank@gmail.com<br>
          </p>

        </div>

        <div class="col-lg-4 col-md-6 footer-info">
          <h3>About NK Bank</h3>
          <p>NK Bank provides premium banking and transaction services both electronic and manual.
            Highest rate of interest and fastest transaction is provided to our customers.
          </p>
          <div class="social-links mt-3">
            <a href="https://github.com/NabhyaKhoria" class="twitter" target="_blank"><i class="bx bxl-github"></i></a>
            <a href="https://www.facebook.com/nkhoria/" class="facebook" target="_blank"><i class="bx bxl-facebook"></i></a>
            <a href="https://www.instagram.com/nabhya_khoria/" class="instagram"><i class="bx bxl-instagram" target="_blank"></i></a>
            <a href="https://www.linkedin.com/in/nabhya-khoria-30a601218/" class="linkedin"><i class="bx bxl-linkedin" target="_blank"></i></a>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="container">
    <div class="copyright">
      &copy; Copyright <strong><span>NK Bank</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      Designed by <a href="https://www.linkedin.com/in/nabhya-khoria-30a601218/" target="_blank">Nabhya Khoria</a>
    </div>
  </div>
</footer>
<!-- End Footer -->
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'banking/assets/vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'banking/assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'banking/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'banking/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'banking/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'banking/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'banking/assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'banking/assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'banking/assets/js/main.js' %}"></script>

</body>

</html>